[package]
name = "implicit-surface-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
approx = "0.5.1"
clap = { version = "4.5.20", features = ["derive"] }
config = "0.14.0"
rand = "0.8.5"
serde = "1.0.210"
serde_derive = "1.0.210"
